language: go

go:
  - 1.6
  - tip

install:
  - go get github.com/stretchr/testify/
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - script/coverage --coveralls
